"""artistsong table

Revision ID: e17a21020b47
Revises: 5af6ea52a1b9
Create Date: 2021-02-05 13:24:09.912751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17a21020b47'
down_revision = '5af6ea52a1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=64), nullable=True),
    sa.Column('song', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['artist'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['song'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_song')
    # ### end Alembic commands ###
