"""fix ArtistSong model

Revision ID: e7431bcbbbc9
Revises: e17a21020b47
Create Date: 2021-02-05 13:41:30.415576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7431bcbbbc9'
down_revision = 'e17a21020b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_song', sa.Column('artist_id', sa.String(length=64), nullable=True))
    op.add_column('artist_song', sa.Column('song_id', sa.String(length=64), nullable=True))
    op.drop_constraint(None, 'artist_song', type_='foreignkey')
    op.drop_constraint(None, 'artist_song', type_='foreignkey')
    op.create_foreign_key(None, 'artist_song', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'artist_song', 'song', ['song_id'], ['id'])
    op.drop_column('artist_song', 'song')
    op.drop_column('artist_song', 'artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_song', sa.Column('artist', sa.VARCHAR(length=64), nullable=True))
    op.add_column('artist_song', sa.Column('song', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'artist_song', type_='foreignkey')
    op.drop_constraint(None, 'artist_song', type_='foreignkey')
    op.create_foreign_key(None, 'artist_song', 'artist', ['artist'], ['id'])
    op.create_foreign_key(None, 'artist_song', 'song', ['song'], ['id'])
    op.drop_column('artist_song', 'song_id')
    op.drop_column('artist_song', 'artist_id')
    # ### end Alembic commands ###
